change makefile

diff --git a/module3_task2/Makefile b/module3_task2/Makefile
--- a/module3_task2/Makefile
+++ b/module3_task2/Makefile
@@ -1,53 +1,32 @@
-GO=go
-TARGET=awesome-api
-RM=rm -rf
-MAKE=make
-COVERAGE=coverage
-HUGO=hugo
-
-build:	## Generate the source code of the application to a binary.
-	$(GO) mod tidy
-	$(MAKE) check && $(HUGO) && $(GO) build -o $(TARGET)
-
-run:	## Run the application in background by executing the binary.
-	./$(TARGET) >./$(TARGET).log 2>&1 &
-
-post:	## Create a new blog post whose filename and title come from the environment variables POST_TITLE and POST_NAME
-	$(HUGO) new posts/$(POST_NAME).md
-	sed -i '2s/.*/title: "$(POST_TITLE)"/' content/posts/$(POST_NAME).md
-
-stop:	## Stop the application.
-	@pkill $(TARGET)
-
-clean:	## Stop the application. Delete the binary and the log file.
-	@if pgrep -x $(TARGET) > /dev/null; then \
-		pkill $(TARGET); \
-	fi
-	@$(RM) $(TARGET) $(TARGET).log $(COVERAGE)-units.out $(COVERAGE)-integrations.out dist/ *~
-
-test:	## Test the application.
-	$(MAKE) unit-tests
-	$(MAKE) integration-tests
-	$(MAKE) validate
-
-unit-tests: ## Run unit tests
-	go test -v -short -coverprofile=$(COVERAGE)-units.out
-
-integration-tests: ## Run integration tests
-	go test -v -coverprofile=$(COVERAGE)-integrations.out
-
-lint:	## Lint go markdown code
+build:   ## Generate the website from the markdown and configuration files in the directory dist/
+	go build
+	hugo > /dev/null 2>&1
+	make check
+clean:    ## Cleanup the content of the directoy dist/
+	rm -rf ./dist/ awesome-api awesome-api.log coverage-units.out coverage-integrations.out
+	make stop
+post:     ## Create a new blog post whose filename and title come from the environment variables POST_TITLE and POST_NAME
+	hugo new posts/$(POST_NAME).md
+	sed -i '/title:/c\title: "$(POST_TITLE)"' content/posts/$(POST_NAME).md
+check: ## Checking markdown files
+	markdownlint content/ && markdown-link-check content/posts/*.md
+validate: ## validates using Holberton tool
+	python3 opt/W3C-Validator/w3c_validator.py dist/index.html || true
+run: ## runs the api and logs it
+	./awesome-api > ./awesome-api.log 2>&1 &
+stop: ## kills the process with PID number
+	pkill awesome-api
+lint: ## check for potential errors
 	markdownlint -f DEPLOY.md README.md || true
-
-check:	## Lint markdonw source, check dead links
-	markdownlint ./content/posts/*.md
-	find content -name \*.md -print0 | xargs -0 -n1 markdown-link-check
-
-validate:	## Validate the file dist/index.html using the command line Holberton’s W3C Validator.
-	python3 ./w3c_validator.py ./dist/index.html || true
-
-package:	## Produce awesome-website.zip containing awesome-api and dist directory
-	zip -FSr awesome-website.zip . -i dist/ awesome-api
-
-help:	## Show this help usage.
-	@sed -ne '/@sed/!s/## //p' $(MAKEFILE_LIST)
+test: ## test hitting the endpoint
+	make unit-tests
+	make integration-tests
+	make validate
+unit-tests: ## run unit-tests
+	go test -v -short -coverprofile=coverage-units.out
+integration-tests: ## run intregrated tests
+	go test -v  -coverprofile=coverage-integrations.out
+package: build ## compile everything and zipit
+	zip -r awesome-website.zip dist/ awesome-api 
+help: ## Display this help
+	@fgrep -h "##" $(MAKEFILE_LIST) | sed -e 's/\(\:.*\#\#\)/\:\ /' | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
